### ISSUE TITLE
Offer to merge repos

### ISSUE THREAD

**Issue by quobit** [ligurio/awesome-openbsd#2]
Hi @ligurio !

I am the owner of [awesome-openbsd](https://github.com/quobit/awesome-openbsd) (CC0 licensed).

Some weeks ago I found your repo (as I noted on my own [issue](https://github.com/quobit/awesome-openbsd/issues/1)). I wonder if you would be interested in our repos being merged.

Regards.

**Comment by ligurio** [comment]
Hi, @quobit! I have no objections regarding merge. Could you send your list of OpenBSD resources and send a pull request with absent items?

**Comment by quobit** [comment]
Great! I'll do it as soon as I can.

**Comment by MindTooth** [comment]
How about that merge guys? :)
