### ISSUE TITLE
Talks and interviews playlist

### ISSUE THREAD

**Issue by quobit** [ligurio/awesome-openbsd#28]
Here we have a playlist with 90+ videos (updated with Dante's recently-added-here video) https://www.youtube.com/playlist?list=PLbET-7keUM8qdq16cDrx-dw2SVXBLH4hk
@ligurio what should we do? (it seems a pretty comprehensive list)

- select a subset to be included in awesome-openbsd
- or just add that playlist (and maybe remove the video section)

**Comment by ligurio** [comment]
Hi! I have no objections to include a link to the playlist.

**Comment by quobit** [comment]
Added
