### ISSUE TITLE
About OpenBSD based projects

### ISSUE THREAD

**Issue by FabioLolix** [ligurio/awesome-openbsd#30]
Hello

https://github.com/ligurio/awesome-openbsd#openbsd-based-projects

RTMX, ATMNIS and Security Router are no longer active

Calyptix Security firewall link is 404

M:Tier OpenBSD thin client source link is not reachable https://opensource.mtier.org/mtc.html

MirOS, Bitring and flashboot are no longer developed, maybe indicate what is discontinued without removing it from the list (for the open stuff)

**Comment by ligurio** [comment]
Oh, you are right. Could create a PR with fix?

**Comment by qbit** [comment]
Calyptix stuff is still active and built with OpenBSD :D  https://www.calyptix.com/products/ would be a better link, i'll submit a PR after confirming.

**Comment by qbit** [comment]
PR created: https://github.com/ligurio/awesome-openbsd/pull/31

**Comment by quobit** [comment]
@ligurio shouldn't we close this issue? All linkrot was removed

**Comment by ligurio** [comment]
@quobit sure, let's close it
